name: Lint
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint